//AUTH_ACTION
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CHECK_USER = "CHECK_USER";
export const AUTH_LOADING = "AUTH_LOADING"

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LOGOUT = "LOGOUT";

//USER_ACTION
export const FEEDBACK_FORM_LOADING = "FEEDBACK_FORM_LOADING";
export const FEEDBACK_FORM_SUBMIT_SUCCESS = "FEEDBACK_FORM_SUBMIT";
export const FEEDBACK_FORM_SUBMIT_ERR = "FEEDBACK_FORM_SUBMIT";

//USER_INFO_UPDATE
export const UPDATE_USER_FORM_LOADING = "FEEDBACK_FORM_LOADING";
export const UPDATE_USER_FORM_SUCCESS = "FEEDBACK_FORM_SUBMIT";
export const UPDATE_USER_FORM_ERR = "FEEDBACK_FORM_SUBMIT";